#!/bin/bash
# Install YouTube Terraform Provider for local development and CI

set -e

# CI mode flag (set via environment variable)
CI_MODE="${CI_MODE:-false}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored output
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
print_info "Checking prerequisites..."

# Check Go installation
if ! command -v go &> /dev/null; then
    print_error "Go is not installed. Please install Go 1.24+ from https://golang.org/dl/"
    exit 1
fi

GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
print_success "Go ${GO_VERSION} detected"

# Check Terraform installation (skip in CI mode)
if [ "$CI_MODE" != "true" ]; then
    if ! command -v terraform &> /dev/null; then
        print_warning "Terraform is not installed. Install from https://www.terraform.io/downloads"
    else
        TF_VERSION=$(terraform version -json | grep -o '"version":"[^"]*' | cut -d'"' -f4)
        print_success "Terraform ${TF_VERSION} detected"
    fi
fi

# Get project root directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

print_info "Project root: ${PROJECT_ROOT}"

# Navigate to project root
cd "$PROJECT_ROOT"

# Download dependencies
print_info "Downloading Go dependencies..."
go mod tidy
print_success "Dependencies updated"

# Build provider
print_info "Building provider..."
go install
if [ $? -eq 0 ]; then
    print_success "Provider built successfully"
else
    print_error "Failed to build provider"
    exit 1
fi

# Detect Go binary path
if [ "$CI_MODE" = "true" ]; then
    GOBIN="${GOBIN:-/opt/media-factory/terraform/providers}"
else
    GOBIN="${GOBIN:-$(go env GOPATH)/bin}"
fi

# Detect the actual binary name (based on module name in go.mod)
MODULE_NAME=$(grep "^module" "$PROJECT_ROOT/go.mod" | awk '{print $2}')
BINARY_NAME=$(basename "$MODULE_NAME")
PROVIDER_BINARY="${GOBIN}/${BINARY_NAME}"

# Create provider directory in CI mode
if [ "$CI_MODE" = "true" ]; then
    mkdir -p "$GOBIN"
    print_info "Created CI provider directory: ${GOBIN}"
fi

if [ ! -f "$PROVIDER_BINARY" ]; then
    print_error "Provider binary not found at ${PROVIDER_BINARY}"
    print_info "Looking for binaries in ${GOBIN}..."
    ls -la "${GOBIN}" | grep terraform || true
    exit 1
fi

print_success "Provider binary: ${PROVIDER_BINARY}"

# Setup .terraformrc for development (skip in CI mode)
if [ "$CI_MODE" != "true" ]; then
    TERRAFORMRC="${HOME}/.terraformrc"
    BACKUP_TERRAFORMRC="${HOME}/.terraformrc.backup.$(date +%s)"

    print_info "Configuring Terraform CLI for local development..."

    # Backup existing .terraformrc if it exists
    if [ -f "$TERRAFORMRC" ]; then
        cp "$TERRAFORMRC" "$BACKUP_TERRAFORMRC"
        print_warning "Existing .terraformrc backed up to ${BACKUP_TERRAFORMRC}"
    fi

    # Create or update .terraformrc
    cat > "$TERRAFORMRC" << EOF
# Terraform CLI Configuration for YouTube Provider Development
# Auto-generated by install-local-provider.sh

provider_installation {
  # Use local development build
  dev_overrides {
    "registry.terraform.io/fishstock-network/youtube-terraform-provider" = "${GOBIN}"
  }

  # For all other providers, install normally
  direct {}
}
EOF

    print_success "Terraform CLI configured at ${TERRAFORMRC}"
else
    print_info "CI mode: Skipping .terraformrc configuration"
fi

# Print final instructions
echo ""
print_success "=========================================="
print_success "Provider Installation Complete!"
print_success "=========================================="
echo ""
print_info "Provider binary location: ${PROVIDER_BINARY}"

if [ "$CI_MODE" = "true" ]; then
    print_info "CI Mode: Provider installed to ${GOBIN}"
else
    print_info "Terraform config: ${TERRAFORMRC}"
    echo ""
    print_info "Next steps:"
    echo "  1. Navigate to examples directory:"
    echo "     cd ${PROJECT_ROOT}/examples"
    echo ""
    echo "  2. Edit playlist.tf with your YouTube access token"
    echo ""
    echo "  3. Initialize and apply:"
    echo "     terraform init"
    echo "     terraform plan"
    echo "     terraform apply"
    echo ""
    print_warning "Note: Terraform will show dev_overrides warnings - this is expected during development"
    echo ""
    print_info "To rebuild provider after code changes:"
    echo "  cd ${PROJECT_ROOT} && go install"
    echo ""
    print_info "To restore original .terraformrc:"
    if [ -f "$BACKUP_TERRAFORMRC" ]; then
        echo "  mv ${BACKUP_TERRAFORMRC} ${TERRAFORMRC}"
    fi
fi
echo ""
